"""Initial migration.

Revision ID: 15209d3bd788
Revises: 
Create Date: 2020-11-16 11:27:52.219478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15209d3bd788'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('contact_phone', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('nic_passport_path', sa.String(length=255), nullable=True),
    sa.Column('cv_path', sa.String(length=255), nullable=False),
    sa.Column('diplomas_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('blood_group', sa.String(length=3), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('marital_status', sa.String(length=1), nullable=False),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('person_to_contact_name', sa.String(length=100), nullable=False),
    sa.Column('person_to_contact_phone', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('consultation',
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('consultation_date', sa.Date(), nullable=False),
    sa.Column('result1', sa.String(length=255), nullable=False),
    sa.Column('result2', sa.String(length=255), nullable=False),
    sa.Column('result3', sa.String(length=255), nullable=False),
    sa.Column('other_observation', sa.Text(), nullable=False),
    sa.Column('syptoms', sa.String(length=255), nullable=False),
    sa.Column('consultation_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('consultation_id')
    )
    op.create_table('past_history',
    sa.Column('past_history_id', sa.Integer(), nullable=False),
    sa.Column('past_history_type', sa.String(length=255), nullable=False),
    sa.Column('past_history_particular_observation', sa.String(length=255), nullable=False),
    sa.Column('past_history_year', sa.Date(), nullable=False),
    sa.Column('past_history_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['past_history_owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('past_history_id')
    )
    op.create_table('report_case',
    sa.Column('report_case_id', sa.Integer(), nullable=False),
    sa.Column('report_reason', sa.Text(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_case_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_case_owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_case')
    op.drop_table('past_history')
    op.drop_table('consultation')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
